name: sbom

on:
  push:
    branches:
      - main

jobs:
  gen:
    name: Generate and Upload SBOM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1
      - name: Setup toolchain
        uses: actions-rust-lang/setup-rust-toolchain@ecabd13d1c56bd1345c230e542e9144811ad706f #v2.0.0
      - name: Setup cyclondx
        uses: taiki-e/cache-cargo-install-action@9ee83daaa7b96a6fab930949ecf1122bba04a389 #v3.0.8
        with:
          tool: cargo-cyclonedx@0.5.9
      - name: Generate SBOM
        run: cargo cyclonedx --all --all-features -f json --override-filename sbom-$VERSION
      - name: Archive SBOM
        with:
          name: sbom
          path: sbom-${{ github.sha }}.json
      - name: Upload SBOM
        with:
          serverHostname: 'back.vulns.gronner.dev'
          apiKey: ${{ secrets.DEPENDENCYTRACK_APIKEY }}
          project: '0ecb8862-d13a-4c3b-8699-9e31a0cb93c7'
          bomFilename: sbom-${{ github.sha }}.json
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a #v7.0.1
        uses: DependencyTrack/gh-upload-sbom@d8935b70f527d6aca6bbef5ab02db3933c9a8626 #v4.2.0

